{% set name = "pyrdfa3" %}
{% set version = "3.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64712d1a4bf21829652b39715bada6e7c03bcf19cb49f962c190a38f46172243

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=59.6.0
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.25.1
    - rdflib >=6.1.1
    - html5lib >=1.1

test:
  imports:
    - pyRdfa
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/prrvchr/pyrdfa3/
  summary: pyRdfa distiller/parser library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
